[package]
name = "parquet-record"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Library for parquet serialization of structs"
license = "MIT"

[lib]
name = "parquet_record"
path = "src/lib.rs"

[dependencies]
parquet = "57"
arrow = { version = "57", features = ["ipc"] }
bytes = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam-channel = "0.5.15"
rayon = "1.11.0"

